minimumReleaseAge: 1440

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - '@suites/di.nestjs'
  - '@suites/doubles.vitest'
  - '@swc/core'
  - esbuild
  - lefthook
  - nestjs-pino
  - protobufjs
